#!/usr/bin/env bash
# Bash script to Install and configure HAproxy on your lb-01 server.
sudo apt-get update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
sudo chown -R ubuntu /etc/haproxy
sudo echo "
frontend web-frontend
        bind *:80
        mode http
        default_backend web-backend
backend web-backend
        balance roundrobin
        server 1419-web-01 100.26.254.249:80 check
        server 1419-web-02 54.90.46.202:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
